# Generated by Django 3.1.7 on 2021-04-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Contest Title', max_length=200)),
                ('imageUrl', models.CharField(help_text='Contest ImageUrl', max_length=300)),
                ('tags', models.JSONField(help_text='Contest Tag', max_length=500)),
                ('summary', models.JSONField(help_text='Contest Summary', max_length=500)),
                ('detail', models.JSONField(help_text='Contest Detail', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
