# Generated by Django 3.2 on 2021-04-19 05:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contest_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='data published'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageUrl', models.ImageField(blank=True, null=True, upload_to='images')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contest_api.contest')),
            ],
        ),
    ]
